dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libusb-1.0-0-dev

env:
  matrix:
    - WITH_FTDI=ON
    - WITH_FTDI=OFF

install: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libusb; fi
    
os: 
  - linux
  - osx

script: 
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/_install -DStandaloneApp=YES -DWithFTDI=$WITH_FTDI
  - make all install
